(function(d,f){d.HAPRadioData=function(g,C){function D(){var a=e.path;";"==a.substring(a.length-1)&&(a=a.substring(0,a.length-1));"/"==a.substring(a.length-1)&&(a=a.substring(0,a.length-1));if(g.enableCors){d.radioDataXHR&&d.radioDataXHR.abort();var c=new XMLHttpRequest;c.onerror=function(a){};c.onreadystatechange=function(){if(4===this.readyState){if(200===this.status){if(e.version&&1==e.version)var a=c.responseText.split(","),l=a[6];else a=JSON.parse(c.responseText),l=a.songtitle;x=a;var u=l.split("-");
a=f.trim(u[0]);u=f.trim(u[1]);h={artist:a,title:u,thumb:null};n?n!=l?g.getRadioArtwork?r(a,u):m||f(p).trigger("HAPRadioData.DATA_READY",h):console.log("data hasnt changed"):g.getRadioArtwork?r(a,u):m||f(p).trigger("HAPRadioData.DATA_READY",h)}n=l}else v||(k&&clearInterval(k),k=setInterval(function(){D()},z))};if(e.version&&1==e.version)c.open("GET",w[t]+a+"/7.html",!0);else{var l=g.sid||"1";c.open("GET",w[t]+a+"/stats?sid="+l+"&json=1",!0)}c.send();d.radioDataXHR=c}else l=e.sid||"1",f.ajax({dataType:"jsonp",
url:a+"/stats?sid="+l+"&json=1",success:function(a){console.log(a);var b=a.songtitle;x=a;var l=a.songtitle.split("-");a=f.trim(l[0]);l=f.trim(l[1]);h={artist:a,title:l,thumb:null};n?n!=b?g.getRadioArtwork?r(a,l):m||f(p).trigger("HAPRadioData.DATA_READY",h):console.log("data hasnt changed"):g.getRadioArtwork?r(a,l):m||f(p).trigger("HAPRadioData.DATA_READY",h);n=b},error:function(){console.log("Error getShoutcastData")}})}function B(){var a=e.path;";"==a.substring(a.length-1)&&(a=a.substring(0,a.length-
1));"/"==a.substring(a.length-1)&&(a=a.substring(0,a.length-1));d.radioXHR&&d.radioXHR.abort();var c=new XMLHttpRequest;c.onerror=function(a){};c.onreadystatechange=function(){if(4===this.readyState)if(200===this.status){if(-1<this.responseText.indexOf('{"icestats":')){var a=JSON.parse(this.responseText);if(void 0===a.icestats.source.length)var b=a.icestats.source;else{var c,d=a.icestats.source.length;for(c=0;c<d;c++)if(0<=a.icestats.source[c].listenurl.indexOf(e.mountpoint)){b=a.icestats.source[c];
break}}x=b;if(b.yp_currently_playing)var q=b.yp_currently_playing;else a=b.artist,b=b.title,a&&b?q=a+"-"+b:b&&(q=b)}else-1<this.responseText.indexOf('class="streamdata"')?-1<this.responseText.indexOf("Mount Point /"+e.mountpoint)&&(b=this.responseText.substr(this.responseText.indexOf("Mount Point /"+e.mountpoint)),b=b.substr(b.indexOf("Current Song:")),b=b.substr(b.indexOf('<td class="streamdata">')+23),b=b.substr(0,b.indexOf("</td>")),HAPUtils.isEmpty(b)||(q=b)):-1<this.responseText.indexOf('class="streamstats"')&&
-1<this.responseText.indexOf("Mount Point /"+e.mountpoint)&&(b=this.responseText.substr(this.responseText.indexOf("Mount Point /"+e.mountpoint)),b=b.substr(b.indexOf("Currently playing:")),b=b.substr(b.indexOf('<td class="streamstats">')+24),b=b.substr(0,b.indexOf("</td>")),HAPUtils.isEmpty(b)||(q=b));q?(b=q.split("-"),a=f.trim(b[0]),b=f.trim(b[1]),h={artist:a,title:b,thumb:null},n?n!=q&&(g.getRadioArtwork?r(a,b):m||f(p).trigger("HAPRadioData.DATA_READY",h)):g.getRadioArtwork?r(a,b):m||f(p).trigger("HAPRadioData.DATA_READY",
h),n=q):(h={artist:E,title:F,thumb:null},m||f(p).trigger("HAPRadioData.DATA_READY",h))}else 404==this.status&&"Not Found"==this.statusText?(console.log(A[y]+" does not exist!"),y++,A[y]?v||(k&&clearInterval(k),B()):(h={artist:E,title:F,thumb:null},m||f(p).trigger("HAPRadioData.DATA_READY",h))):v||(k&&clearInterval(k),k=setInterval(function(){B()},z))};g.enableCors?c.open("GET",w[t]+a+A[y],!0):c.open("GET",a+A[y],!0);c.send();d.radioXHR=c}function G(){d.radioDataXHR&&d.radioDataXHR.abort();var a=new XMLHttpRequest;
a.onerror=function(a){};a.onreadystatechange=function(){if(4===this.readyState)if(200===this.status){var c=JSON.parse(a.responseText),b=c.artist,d=c.title,e=b+" - "+d,q=c.thumb||null;x=c;h={artist:b,title:d,thumb:q};n?n!=e&&(g.getRadioArtwork&&null==q?r(b,d):m||f(p).trigger("HAPRadioData.DATA_READY",h)):g.getRadioArtwork&&null==q?r(b,d):m||f(p).trigger("HAPRadioData.DATA_READY",h);n=e}else v||(k&&clearInterval(k),k=setInterval(function(){G()},z))};var c="http://www.radiojar.com/api/stations/"+e.mountpoint+
"/now_playing/";g.enableCors?a.open("GET",w[t]+c,!0):a.open("GET",c,!0);a.send();d.radioDataXHR=a}function r(a,c){if(!m){a=H(a);c=I(c);var l=w[t]+"https://itunes.apple.com/search?type=jsonp&term=="+encodeURI(a)+"-"+encodeURI(c)+"&media=music&limit=1",b=new XMLHttpRequest;b.onerror=function(a){};b.onreadystatechange=function(){if(4===this.readyState)if(200===this.status){var b=JSON.parse(this.responseText);if(b.resultCount){var d=C.width();d=HAPUtils.closestNumber(g.artworkSize,d);b=b.results[0].artworkUrl100.replace("100x100",
d+"x"+d)}else b=e.thumbDefault;h.thumb=b;m||f(p).trigger("HAPRadioData.DATA_READY",h);k&&clearInterval(k);k=setInterval(function(){p.getData()},z);v=!0}else 403===this.status&&(t++,t>w.length-1&&(t=0),r(a,c))};b.open("GET",l,!0);b.send();d.artworkDataXHR=b}}function H(a){a=a.toLowerCase();a=f.trim(a);a.includes("&")?a=a.substr(0,a.indexOf(" &")):a.includes("feat")?a=a.substr(0,a.indexOf(" feat")):a.includes("ft.")&&(a=a.substr(0,a.indexOf(" ft.")));return a}function I(a){a=a.toLowerCase();a=f.trim(a);
a.includes("&")?a=a.replace("&","and"):a.includes("(")?a=a.substr(0,a.indexOf(" (")):a.includes("ft")&&(a=a.substr(0,a.indexOf(" ft")));return a}var p=this;HAPUtils.isMobile();var e,x,h,n,v,m,A=["/status-json.xsl","/status.xsl"],y=0,w=g.cors.split(",").map(function(a){return a.trim()}),t=0,k,z=g.lastPlayedInterval,E=g.defaultSongArtist,F=g.defaultSongTitle;0==C.length&&(g.getRadioArtwork=!1);this.getData=function(a){a&&(e=a);m=!1;"shoutcast"==e.type?D():"icecast"==e.type?B():"radiojar"==e.type?G():
console.log("HAPRadioData unknown radio data!")};this.destroy=function(){m=!0;k&&clearInterval(k);k=null;d.radioDataXHR&&(d.radioDataXHR.abort(),delete d.radioDataXHR);d.artworkDataXHR&&(d.artworkDataXHR.abort(),delete d.artworkDataXHR);t=0;v=!1;n=null};this.getRadioData=function(){return x}}})(window,jQuery);